### ISSUE TITLE
Add DGS-Framework compatible starter

### ISSUE THREAD

**Issue by setchy** [tailrocks/graphql-java-datetime#41]
We heavily use this library with our [graphql-java-kickstart](https://github.com/graphql-java-kickstart) based APIs and it's been great.

For new graphql services, we've been experimenting with using the Netflix [dgs-framework](https://github.com/Netflix/dgs-framework).

I'm raising this issue to see if there is an appetite to create/split into two separate starters, which would support either graphql-java-kickstart or dgs-framework

**Comment by donbeave** [comment]
Hi, @setchy !

It's an amazing idea! I think we can rename the current one `graphql-datetime-spring-boot-starter` to `graphql-datetime-kickstart-spring-boot-starter` and add another one for dgs framework. I will also add one more module for Micronaut, because mostly I'm using this `graphql-java-datetime` library with Micronaut nowadays.

**Comment by setchy** [comment]
@donbeave awesome!  I have given this a bit more thought and concluded that it made more sense to add an autoconfig datetime module to the `dgs-framework` - mainly because their release cycle is very frequently and we'd want to keep all of the dgs-framework modules insync.

Here is a draft PR I've put together - https://github.com/Netflix/dgs-framework/pull/797

**Comment by donbeave** [comment]
@setchy it looks like the original PR was closed, if you are interested to add this module to the current project, I will be happy to see it here, on top of that I can help you with the implementation of adding a sample project.

I'm planning to release a `5.0.0` version with support three main starters:

1) GraphQL Kickstart
2) Spring Boot GraphQL
3) DGS Framework

**Comment by setchy** [comment]
@donbeave - most certainly - happy to work with you and contribute a DGS starter.

**Comment by donbeave** [comment]
@setchy amazing! How can I help you? It looks like most of the job already finished by you in that PR.

**Comment by donbeave** [comment]
@setchy I made some restructuring of the current plugin, now it supports both [GraphQL Java Kickstart](https://github.com/graphql-java-kickstart) and [official Spring for GraphQL](https://spring.io/projects/spring-graphql).

You can create a PR with your implementation of the DGS starter, I will be happy to release it together in the next version.

**Comment by setchy** [comment]
@donbeave - awesome, thanks for restructuring the project.  I'll work through adding DGS shortly.
