### ISSUE TITLE
Version 5.0.0-SNAPSHOT not contained in snapshot repo

### ISSUE THREAD

**Issue by jheinzel** [tailrocks/graphql-java-datetime#80]
Although I included the snapshot repo https://oss.sonatype.org/content/repositories/snapshots to my `settings.xml` maven cannot find the current version of `com.tailrocks.graphql:graphql-datetime-spring-boot-starter:5.0.0-SNAPSHOT`.

**Comment by donbeave** [comment]
@jheinzel just published it here: https://s01.oss.sonatype.org/content/repositories/snapshots/com/tailrocks/graphql/

**Comment by jheinzel** [comment]
Thanks. After adding the snapshot repo you mentioned, everything works as expected.
