### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by Tobiaswec** [tailrocks/graphql-java-datetime#84]
The library/plugin can not be found on maven, thats why the sonatype repository needs to be added. Maybe you could mention that in the readme for other users.

Gradle:
`
repositories {
	mavenCentral()
	maven {
		url "https://s01.oss.sonatype.org/content/repositories/snapshots"
	}
}
`

**Comment by setchy** [comment]
The v5.0.0 release was waiting for spring graphql 1.0 to be released. Now that this milestone has been reached, we should be able to publish 5.0.0 of this library.

**Comment by donbeave** [comment]
Released 5.0.0: https://github.com/tailrocks/graphql-java-datetime/releases/tag/v5.0.0
